import { Theme, ThemePanel, Flex } from "@radix-ui/themes";
import "./globals.css";
// import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <Flex className="min-h-full " direction={"column"} gap={"3"}>
          <Theme>
            <Header />
            {children}
          </Theme>
          <Footer />
        </Flex>
      </body>
    </html>
  );
}
